-- Criação do banco
create database Estacionamento_SENAI;
use Estacionamento_SENAI;

-- Criação das tabelas
create table VEICULO(
ID INT PRIMARY KEY AUTO_INCREMENT,
MARCA VARCHAR(120) NOT NULL,
PLACA VARCHAR(50) UNIQUE NOT NULL
);

create table CLIENTE(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(120) NOT NULL,
TELEFONE VARCHAR(50) NOT NULL
);

create table ENTRADA_SAIDA(
ID INT PRIMARY KEY AUTO_INCREMENT,
DT_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
SITUACAO BOOLEAN,
ID_VEICULO INT,
ID_CLIENTE INT
);

-- Criação das chaves estrangeiras
alter table Entrada_saida
ADD CONSTRAINT FK_VEICULO_ID
FOREIGN KEY (ID_VEICULO)
REFERENCES VEICULO(ID)
ON DELETE CASCADE;

alter table Entrada_saida
ADD CONSTRAINT FK_CLIENTE_ID
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID)
ON DELETE CASCADE;